deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - temp_kube_config_file=$(printenv KUBECONFIG)
    - cat $temp_kube_config_file
    - kubectl config get-contexts
    - kubectl config view