deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - printenv
    - ls -ltra
    - echo $KUBECONFIG
    - cat /builds/demos-group/solar-system.tmp/KUBECONFIG
    - kubectl config get-contexts
    - kubectl config use-context path/to/agent/project:agent-name
    - kubectl get pods