deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - printenv KUBECONFIG
    - echo $KUBECONFIG
    - cat /builds/demos-group/solar-system.tmp/KUBECONFIG
    - kubectl config get-contexts
    - kubectl config view
    - kubectl get pods