workflow:
    name: Solar System CICD Pipeline
    rules:
        - if: $CI_BRANCH_NAME == 'main' && $CI_BRANCH_NAME =~ /^feature-*/
          when: always
        - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^feature-*/ && $CI_PIPELINE_SOURCE == 'merge_request_event'
         
variables:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData' 
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: $MASKED_PASSWORD
stages:
    - test

unit-testing:
    stage:
        - test
    image: node:17-alpine3.14
    before_script:
        - npm install
    script:
        - npm test
    