name: ASCII Generator Artwork
on: push
jobs:
  artwork_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Install cowsay program
      run: sudo apt install cowsay -y
    - name: Generator artwork
      run: cowsay -f dog "I saw the cute dog" >> dog.txt
    - name: Verify the File content
      run: grep -i 'dog' dog.txt
    - name: View the content
      run: cat dog.txt
    - name: List file content
      run: ls -lrt