name: ASCII Generator Artwork
on: push
jobs:
  artwork_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Install cowsay program
      run: sudo apt install cowsay -y
    - name: Generator artwork
      run: cowsay -f dragon "I saw the cute dragon" >> dragon.txt
    - name: Verify the File content
      run: grep -i "dragon" dragon.txt
    - name: View the content
      run: cat dragon.txt
    - name: List file content
      run: ls -lrt