name: ASCII Generator Artwork
on: push
jobs:
  build_job_01:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Install cowsay program
      run: sudo apt install cowsay -y
    - name: Generator artwork
      run: cowsay -f dragon "I saw the cute dragon" >> dragon.txt
    - name: upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dragon-text-file
        path: dragon.txt
  test_job_02:
    runs-on: ubuntu-latest
    needs: build_job_01
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file
    - name: Verify the File content
      run: grep -i "dragon" dragon.txt
  deploy_job_03:
    runs-on: ubuntu-latest
    needs: test_job_02
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file
    - name: View the content
      run: cat dragon.txt
    - name: List file content
      run: echo "Deploying..."