name: First cicd workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: list files and read files
      run: |
          echo "welcome to github actions first cicd"
          ls -lrt
          head -10 README.md
    - name: ASHI Generator
      run: cowsay -f dog "I saw the cute dog" > dog.txt